export const HANDLE_SUBMIT_IF_EMAIL = 'HANDLE_SUBMIT_IF_EMAIL';
export const HANDLE_SUBMIT_IF_PASSWORD = 'HANDLE_SUBMIT_IF_PASSWORD';
export const HANDLE_SUBMIT_ELSE = 'HANDLE_SUBMIT_ELSE';
export const HANDLE_SUBMIT_SET = 'HANDLE_SUBMIT_SET';
export const HANDLE_CHANGE = 'HANDLE_CHANGE';